package com.evoai.trainer.ga

import com.evoai.trainer.nn.NeuralNetwork

/**
 * Represents a single Model in the V3 Evolution Engine.
 * Each Model carries a family identity, fitness history (sparkline), and lineage badge.
 *
 * Naming Convention: "Model [familyId] Gen [generationBorn]"
 * Example: "Model 3 Gen 12" — born in generation 12, belongs to family 3.
 */
data class Bot(
    val id: Int,                     // Slot position (0-9) in the 2x5 grid
    val network: NeuralNetwork,
    var fitness: Float = 0f,
    var accuracy: Float = 0f,
    var status: BotStatus = BotStatus.READY,
    val lineage: BotLineage = BotLineage.CLONE,
    val mutationVariance: Float = 0f,
    val parentRank: Int = 0,         // Which elite parent this was cloned from (1 or 2)
    val familyId: Int = 0,           // Family lineage ID (inherits from parent)
    val generationBorn: Int = 0,     // Generation this model was created in
    val fitnessHistory: MutableList<Float> = mutableListOf() // Last N fitness scores for sparkline
) {
    /**
     * Display name following V3 convention: "Model [familyId] Gen [generationBorn]"
     */
    val displayName: String
        get() = "Model $familyId Gen $generationBorn"

    /**
     * Add a fitness score to the sparkline history.
     * Keeps only the last 5 entries.
     */
    fun recordFitness(score: Float) {
        fitnessHistory.add(score)
        if (fitnessHistory.size > 5) {
            fitnessHistory.removeAt(0)
        }
    }

    /**
     * Get the sparkline data as a FloatArray for the custom View.
     */
    fun getSparklineData(): FloatArray = fitnessHistory.toFloatArray()
}

enum class BotStatus {
    READY,
    TRAINING,
    EVALUATED,
    BEST,
    ELIMINATED
}

/**
 * V3 Lineage badges:
 * - LEGACY: One of the Top 2 survivors from the previous generation.
 * - CLONE: An offspring generated by cloning and mutating a Legacy model.
 * - RESET_RANDOM: A completely randomized model (injected when fitness hits 0.00).
 */
enum class BotLineage {
    LEGACY,
    CLONE,
    RESET_RANDOM
}
