package com.evoai.trainer.ga

import com.evoai.trainer.nn.NeuralNetwork

/**
 * Represents a single Model in the V4 Commercial-Grade Evolution Engine.
 *
 * V4 upgrades:
 * - Loss field: Binary Cross-Entropy loss for tiebreaker logic
 * - When two models have same accuracy, lower loss wins (more confident predictions)
 * - Validation accuracy: measured on 20% holdout set for true generalization
 * - Fitness history for sparkline visualization
 * - Family lineage tracking with naming convention
 */
data class Bot(
    val id: Int,                     // Slot position (0-9) in the 2x5 grid
    val network: NeuralNetwork,
    var fitness: Float = 0f,
    var accuracy: Float = 0f,
    var valAccuracy: Float = 0f,     // V4: Accuracy on validation set (20% holdout)
    var loss: Float = Float.MAX_VALUE, // V4: BCE loss — lower is better
    var status: BotStatus = BotStatus.READY,
    val lineage: BotLineage = BotLineage.CLONE,
    val mutationVariance: Float = 0f,
    val parentRank: Int = 0,         // Which elite parent this was cloned from (1 or 2)
    val familyId: Int = 0,           // Family lineage ID (inherits from parent)
    val generationBorn: Int = 0,     // Generation this model was created in
    val fitnessHistory: MutableList<Float> = mutableListOf(), // Last N fitness scores for sparkline
    val lineageChain: String = ""    // V5: Full lineage chain e.g. "Model 1 → Clone Gen 3 → Clone Gen 7"
) {
    /**
     * V5: Display name — shows lineage chain when available, otherwise "Model [familyId] Gen [generationBorn]"
     */
    val displayName: String
        get() = if (lineageChain.isNotEmpty()) lineageChain.take(20) else "Model $familyId Gen $generationBorn"

    /**
     * Add a fitness score to the sparkline history.
     * Keeps only the last 5 entries.
     */
    fun recordFitness(score: Float) {
        fitnessHistory.add(score)
        if (fitnessHistory.size > 5) {
            fitnessHistory.removeAt(0)
        }
    }

    /**
     * Get the sparkline data as a FloatArray for the custom View.
     */
    fun getSparklineData(): FloatArray = fitnessHistory.toFloatArray()

    /**
     * V4: Composite score for ranking — higher accuracy first, then lower loss as tiebreaker.
     * Returns a comparable value: higher is better.
     */
    fun compositeScore(): Float {
        // Primary: accuracy (0-100). Tiebreaker: negative loss (lower loss = higher score).
        // Loss is typically 0.1-5.0, so we scale it to a small fraction for tiebreaking.
        return accuracy - (loss * 0.01f)
    }
}

enum class BotStatus {
    READY,
    TRAINING,
    EVALUATED,
    BEST,
    ELIMINATED
}

/**
 * V4 Lineage badges:
 * - LEGACY: One of the Top 2 survivors from the previous generation.
 * - CLONE: An offspring generated by cloning and mutating a Legacy model.
 * - RESET_RANDOM: A completely randomized model (injected when fitness hits 0.00).
 */
enum class BotLineage {
    LEGACY,
    CLONE,
    RESET_RANDOM
}
