package com.evoai.trainer.ga

import com.evoai.trainer.nn.NeuralNetwork

/**
 * Represents a single BOT in the evolutionary population.
 * Each BOT wraps a Neural Network and tracks its fitness score, lineage, and mutation variance.
 */
data class Bot(
    val id: Int,
    val network: NeuralNetwork,
    var fitness: Float = 0f,
    var accuracy: Float = 0f,
    var status: BotStatus = BotStatus.READY,
    val lineage: BotLineage = BotLineage.MUTATED_CLONE,
    val mutationVariance: Float = 0f,
    val parentRank: Int = 0  // Which elite parent this was cloned from (1 or 2)
)

enum class BotStatus {
    READY,
    TRAINING,
    EVALUATED,
    BEST,
    ELIMINATED
}

/**
 * Lineage indicator tracking how this BOT was created in the current generation.
 * - ELITE_PARENT: One of the top 2 models retained from the previous generation.
 * - MUTATED_CLONE: An offspring generated by cloning and mutating an Elite.
 * - RESET_RANDOM: A completely randomized model (injected when fitness hits 0.00 to prevent stagnation).
 */
enum class BotLineage {
    ELITE_PARENT,
    MUTATED_CLONE,
    RESET_RANDOM
}
